package arbolb;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author enrique7cp@gmail.com
 */
public class Ventana extends javax.swing.JFrame {
    
    int ordenArbol;
    Arbol arbolito = new Arbol(ordenArbol);
    Nodo nodo = new Nodo(ordenArbol);
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        lblOrden.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jpVentana = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnNivel = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        txfInsertar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txfEliminar = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txfBuscar = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txfNivelNodo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txfOrden = new javax.swing.JTextField();
        btnOrden = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMostrar = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        lblOrden = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/arbol3.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 20, 400));

        jpVentana.setBackground(java.awt.SystemColor.activeCaption);
        jpVentana.setForeground(new java.awt.Color(0, 0, 0));
        jpVentana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpVentanaKeyPressed(evt);
            }
        });
        jpVentana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(java.awt.SystemColor.activeCaption);
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir.png"))); // NOI18N
        jButton1.setText("IMPRIMIR ");
        jButton1.setToolTipText("Imprime las claves que se encuentran \nen las hojas del árbol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpVentana.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 180, -1));

        jButton2.setBackground(java.awt.SystemColor.activeCaption);
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/altura.png"))); // NOI18N
        jButton2.setText("ALTURA ÁRBOL");
        jButton2.setToolTipText("Muestra la altura del árbol");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jpVentana.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 180, -1));

        btnNivel.setBackground(java.awt.SystemColor.activeCaption);
        btnNivel.setForeground(new java.awt.Color(255, 255, 255));
        btnNivel.setText("OK");
        btnNivel.setToolTipText("Ingrese el número del cual necesita saber su nivel");
        btnNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelActionPerformed(evt);
            }
        });
        jpVentana.add(btnNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        btnBuscar.setBackground(java.awt.SystemColor.activeCaption);
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("OK");
        btnBuscar.setToolTipText("Ingrese el número que desea buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jpVentana.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        btnEliminar.setBackground(java.awt.SystemColor.activeCaption);
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("OK");
        btnEliminar.setToolTipText("Ingrese el número que desea eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpVentana.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        btnInsertar.setBackground(java.awt.SystemColor.activeCaption);
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setText("OK");
        btnInsertar.setToolTipText("Ingrese una clave para insertar en el árbol");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jpVentana.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, 30));

        txfInsertar.setBackground(java.awt.SystemColor.activeCaption);
        txfInsertar.setForeground(new java.awt.Color(255, 255, 255));
        txfInsertar.setToolTipText("Ingrese una clave para insertar en el árbol");
        txfInsertar.setBorder(null);
        txfInsertar.setCaretColor(new java.awt.Color(255, 255, 255));
        txfInsertar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfInsertarKeyPressed(evt);
            }
        });
        jpVentana.add(txfInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/insertar.png"))); // NOI18N
        jpVentana.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 30, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jpVentana.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N
        jpVentana.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        txfEliminar.setBackground(java.awt.SystemColor.activeCaption);
        txfEliminar.setForeground(new java.awt.Color(255, 255, 255));
        txfEliminar.setToolTipText("Ingrese el número que desea eliminar");
        txfEliminar.setBorder(null);
        txfEliminar.setCaretColor(new java.awt.Color(255, 255, 255));
        txfEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfEliminarKeyPressed(evt);
            }
        });
        jpVentana.add(txfEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 80, 20));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jpVentana.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 80, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        jpVentana.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        txfBuscar.setBackground(java.awt.SystemColor.activeCaption);
        txfBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txfBuscar.setToolTipText("Ingrese el número que desea buscar");
        txfBuscar.setBorder(null);
        txfBuscar.setCaretColor(new java.awt.Color(255, 255, 255));
        txfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfBuscarActionPerformed(evt);
            }
        });
        txfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfBuscarKeyPressed(evt);
            }
        });
        jpVentana.add(txfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 90, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jpVentana.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 90, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/obtenerNivel.png"))); // NOI18N
        jpVentana.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        txfNivelNodo.setBackground(java.awt.SystemColor.activeCaption);
        txfNivelNodo.setForeground(new java.awt.Color(255, 255, 255));
        txfNivelNodo.setToolTipText("Ingrese el número del cual necesita saber su nivel");
        txfNivelNodo.setBorder(null);
        txfNivelNodo.setCaretColor(new java.awt.Color(255, 255, 255));
        txfNivelNodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfNivelNodoKeyPressed(evt);
            }
        });
        jpVentana.add(txfNivelNodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 90, 20));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jpVentana.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 90, 20));

        txfOrden.setBackground(java.awt.SystemColor.activeCaption);
        txfOrden.setForeground(new java.awt.Color(255, 255, 255));
        txfOrden.setToolTipText("Ingrese el nivel del árbol");
        txfOrden.setBorder(null);
        txfOrden.setCaretColor(new java.awt.Color(255, 255, 255));
        txfOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txfOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfOrdenActionPerformed(evt);
            }
        });
        txfOrden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfOrdenKeyPressed(evt);
            }
        });
        jpVentana.add(txfOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, 20));

        btnOrden.setBackground(java.awt.SystemColor.activeCaption);
        btnOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnOrden.setText("OK");
        btnOrden.setToolTipText("Ingrese el nivel del árbol");
        btnOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenActionPerformed(evt);
            }
        });
        jpVentana.add(btnOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Uroob", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Á");
        jpVentana.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 20, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/arreglo.png"))); // NOI18N
        jpVentana.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jpVentana.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 90, 20));

        jLabel10.setFont(new java.awt.Font("Uroob", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("R");
        jpVentana.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Uroob", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("B");
        jpVentana.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Uroob", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("O");
        jpVentana.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Uroob", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("L");
        jpVentana.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 20, -1));

        jLabel14.setFont(new java.awt.Font("Uroob", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("B");
        jpVentana.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel15.setFont(new java.awt.Font("Uroob", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("+");
        jpVentana.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/altura.png"))); // NOI18N
        jpVentana.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txaMostrar.setBackground(java.awt.SystemColor.activeCaption);
        txaMostrar.setColumns(20);
        txaMostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txaMostrar.setForeground(new java.awt.Color(255, 255, 255));
        txaMostrar.setRows(5);
        jScrollPane1.setViewportView(txaMostrar);

        jpVentana.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, 380));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Posicione el cursor sobre cada área de texto");
        jpVentana.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 460, 20));

        lblOrden.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOrden.setForeground(new java.awt.Color(0, 0, 0));
        lblOrden.setText("Orden del árbol actual:");
        jpVentana.add(lblOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 280, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("para las instrucciones.");
        jpVentana.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 240, -1));

        getContentPane().add(jpVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(!txfEliminar.getText().equals("")){
            
            arbolito.Eliminar1(Integer.parseInt(txfEliminar.getText()));
            txfEliminar.setText(""); //limpia el area de texto para ingreso de nuevo número
            txfEliminar.requestFocus();
            JOptionPane.showMessageDialog(null, "El número se eliminó correctamente");
        }else {
            JOptionPane.showMessageDialog(null, "El area de texto está vacío");
            txfEliminar.requestFocus();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Imprime el arbol en un area de texto
        txaMostrar.setText(arbolito.mostrarHojas().getText());
        arbolito.ayudantePrint();
        //arbolito.ayudaPrintHojas();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txfOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfOrdenActionPerformed

    private void btnOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenActionPerformed
        // Manda como parametro el orden del arbol que se pide
        if (!txfOrden.getText().equals("")) {
            ordenArbol = Integer.parseInt(txfOrden.getText());
            arbolito = new Arbol(ordenArbol);
            nodo = new Nodo(ordenArbol);
            lblOrden.setText("Orden del árbol actual: " + ordenArbol);
            lblOrden.setVisible(true);
            txfOrden.setText(""); //limipia el area de texto
            txfOrden.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "El area de texto está vacío");
            txfOrden.requestFocus();
        }
    }//GEN-LAST:event_btnOrdenActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // Inserta una clave al arbol
        if (!txfInsertar.getText().equals("")) {
            arbolito.insertar(Integer.parseInt(txfInsertar.getText()));
            txfInsertar.setText("");
            txfInsertar.requestFocus();
        }else {
            JOptionPane.showMessageDialog(null, "El area de texto está vacío");
            txfInsertar.requestFocus();
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(!txfBuscar.getText().equals("")){
            
            arbolito.ayudanteBuscarr(Integer.parseInt(txfBuscar.getText()));
            txfBuscar.setText(""); //limpia el area de texto para ingreso de otro número
            txfBuscar.requestFocus();
        }else {
            JOptionPane.showMessageDialog(null, "El area de texto está vacío");
            txfBuscar.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelActionPerformed
        // TODO add your handling code here:
        if(!txfNivelNodo.getText().equals("")){
            
            arbolito.getNivel(Integer.parseInt(txfNivelNodo.getText()));
            txfNivelNodo.setText(""); //limpia el area de texto
            txfNivelNodo.requestFocus();
        }else {
            JOptionPane.showMessageDialog(null, "El area de texto está vacío");
            txfNivelNodo.requestFocus();
        }
    }//GEN-LAST:event_btnNivelActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formKeyPressed

    private void jpVentanaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpVentanaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jpVentanaKeyPressed

    private void txfOrdenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfOrdenKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txfOrden.getText().equals("")) {
                ordenArbol = Integer.parseInt(txfOrden.getText());
                arbolito = new Arbol(ordenArbol);
                nodo = new Nodo(ordenArbol);
                lblOrden.setText("Orden del árbol actual: " + ordenArbol);
                lblOrden.setVisible(true);
                txfOrden.setText(""); //limipia el area de texto
                txfOrden.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "El area de texto está vacío");
                txfOrden.requestFocus();
            }
        }
    }//GEN-LAST:event_txfOrdenKeyPressed

    private void txfInsertarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfInsertarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Inserta una clave al arbol
            if (!txfInsertar.getText().equals("")) {
                arbolito.insertar(Integer.parseInt(txfInsertar.getText()));
                txfInsertar.setText("");
                txfInsertar.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "El area de texto está vacío");
                txfInsertar.requestFocus();
            }
        }
    }//GEN-LAST:event_txfInsertarKeyPressed

    private void txfEliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfEliminarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txfEliminar.getText().equals("")) {
                arbolito.Eliminar1(Integer.parseInt(txfEliminar.getText()));

                txfEliminar.setText(""); //limpia el area de texto para ingreso de nuevo número
                txfEliminar.requestFocus();
                JOptionPane.showMessageDialog(null, "El número se eliminó correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "El area de texto está vacío");
                txfEliminar.requestFocus();
            }
        }
    }//GEN-LAST:event_txfEliminarKeyPressed

    private void txfBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfBuscarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txfBuscar.getText().equals("")) {

                arbolito.ayudanteBuscarr(Integer.parseInt(txfBuscar.getText()));
                txfBuscar.setText(""); //limpia el area de texto para ingreso de otro número
                txfBuscar.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "El area de texto está vacío");
                txfBuscar.requestFocus();
            }
        }
    }//GEN-LAST:event_txfBuscarKeyPressed

    private void txfNivelNodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNivelNodoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txfNivelNodo.getText().equals("")) {
                
                arbolito.getNivel(Integer.parseInt(txfNivelNodo.getText()));
                txfNivelNodo.setText(""); //limpia el area de texto
                txfNivelNodo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "El area de texto está vacío");
                txfNivelNodo.requestFocus();
            }
        }
    }//GEN-LAST:event_txfNivelNodoKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        arbolito.ayudanteAltura();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnNivel;
    private javax.swing.JButton btnOrden;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel jpVentana;
    private javax.swing.JLabel lblOrden;
    private javax.swing.JTextArea txaMostrar;
    private javax.swing.JTextField txfBuscar;
    private javax.swing.JTextField txfEliminar;
    private javax.swing.JTextField txfInsertar;
    private javax.swing.JTextField txfNivelNodo;
    private javax.swing.JTextField txfOrden;
    // End of variables declaration//GEN-END:variables
    

    
}


